name: CI/CD Pipeline for Node.js Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Package application
        run: zip -r nodejs-app-build.zip . -x "*.git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nodejs-app-build
          path: nodejs-app-build.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nodejs-app-build

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "nodejs-app"          
          environment_name: "nodejs-app-env"     
          version_label: ${{ github.sha }}       
          region: "us-east-1"                   
          file: "nodejs-app-build.zip"
          wait_for_deploy: true
